version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/service
    env_file:
      - ./.env

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/

volumes:
  postgresdata:
    driver: local
