# Generated by Django 5.0 on 2024-05-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.JSONField(null=True, verbose_name='Содержание отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Просматривал ли отчет модератор'),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate', verbose_name='Шаблон, по которому заполняется отчет'),
        ),
    ]
