# Generated by Django 5.0 on 2024-05-09 22:13

import reports.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_data_report_is_reviewed_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(encoder=reports.utils.DateTimeEncoder, null=True, verbose_name='Содержание отчета'),
        ),
    ]
