# Generated by Django 5.0 on 2024-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='version',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен ли шаблон'),
        ),
    ]
