# Generated by Django 5.0 on 2024-06-11 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_reporttemplate_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='report_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания отчетного периода'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='report_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала отчетного периода'),
        ),
    ]
