# Generated by Django 5.0 on 2024-06-27 20:38

import django.db.models.deletion
import reports.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reporttemplate_report_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название шаблона статистики', verbose_name='Название шаблона статистики')),
                ('template_file', models.FileField(help_text='Загрузите файл шаблона статистики в формате docx', upload_to='stats_templates', verbose_name='Файл шаблона статистики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон статистики',
                'verbose_name_plural': 'Шаблоны статистики',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(encoder=reports.utils.DateTimeEncoder, null=True, verbose_name='Содержание статистики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate', verbose_name='Пользователь')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.statstemplate', verbose_name='Шаблон, по которому заполняется статистика')),
            ],
        ),
    ]
