# Generated by Django 5.0 on 2024-07-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_statstemplate_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
